<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/hierarchical.master" AutoEventWireup="true" CodeFile="CourseIntroduction.aspx.cs" Inherits="Introduction_CourseIntroduction" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
     <h3>Course Introduction</h3>


<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 11.5px; color: rgb(48, 48, 48); font-family: &quot;Whitney SSm A&quot;, &quot;Whitney SSm B&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4750099329" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">Introduction to CS6460 (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=WxYy9A20c54" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289178" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">Readiness Questions (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=wnCSVssDPv8" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289179" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">An Experiment in Educational Technology (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=mkYEVWZ6tYI" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4840768708" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">Learning Goals (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=yAxck_1RYCo" style="box-sizing: border-box; background: transparent; color: rgb(20, 94, 127); text-decoration: underline; outline: -webkit-focus-ring-color auto 5px; outline-offset: -2px;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289181" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">Learning Outcomes (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=6IVOnxiYhYs" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289182" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">Learning Assessments (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=50a0Ai2RXgU" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289183" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">What is Educational Technology? (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=M9Bvrtknm_4" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289183" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">The Class Project (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=SNJj8B0mGhU" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289185" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">The Structure of the Class (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=KCcc6oqx6qk" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289186" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">Mentorship (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=H0d2OHt65OU" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289187" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">The Course Library (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=CzFXhfRU9L8" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
    <li style="box-sizing: border-box;"><a href="https://www.udacity.com/course/viewer#!/c-ud915/l-4758509302/m-4797289188" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">Let&#39;s Get Started! (Video)</a><span class="Apple-converted-space">&nbsp;</span>|<span class="Apple-converted-space">&nbsp;</span><a href="https://www.youtube.com/watch?v=VK5b5ZQEI7M" style="box-sizing: border-box; background: transparent; color: rgb(31, 143, 193); text-decoration: none;">(On YouTube)</a></li>
</ul>


</asp:Content>

